version: '3'

services:
  db:
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    tty: true
    restart: always
    #volumes:
    #  - ./mysql-data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - redemoinho
    ports:
      - "3306:3306"  

  app:
    build: 
      context: node
    container_name: app  
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh
    command: "node index.js"
    tty: true
    networks:
      - redemoinho
    ports:
      - "3000:3000"    
    depends_on:
      - db  

  webserver:  
    build:
        context: nginx
    container_name: webserver
    #entrypoint: dockerize -wait tcp://app:3000 -timeout 20s docker-entrypoint.sh
    tty: true
    ports:
      - "8080:80"
    networks:
      - redemoinho
    depends_on:
      - app  

networks:
  redemoinho:
    driver: bridge